name: "E2E Test"
on:
    schedule:
        - cron:  '0 4 * * *'
    workflow_dispatch:

jobs:
    build:
        if: github.repository == 'alfio-event/alf.io'
        strategy:
            matrix:
                browser: ['chrome', 'firefox', 'safari']
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/cache@v4
              with:
                  path: ~/.gradle/caches
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
                  restore-keys: |
                      ${{ runner.os }}-gradle-
            - uses: actions/cache@v4
              with:
                  path: ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradlew') }}
                  restore-keys: |
                      ${{ runner.os }}-gradlew-
            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  java-version: 17
                  distribution: temurin
            - name: 'BrowserStack Env Setup'
              uses: 'browserstack/github-actions/setup-env@master'
              with:
                  username: ${{ secrets.BROWSERSTACK_USERNAME }}
                  access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
            - name: Build with Gradle
              run: ./gradlew test -Dspring.profiles.active=travis,e2e --tests NormalFlowE2ETest
              env:
                  E2E_SERVER_APIKEY: ${{ secrets.E2E_SERVER_APIKEY }}
                  E2E_SERVER_URL: ${{ secrets.E2E_SERVER_URL }}
                  E2E_BROWSER: ${{matrix.browser}}